# Generated by Selenium IDE - Modified for Headless & SSL Bypass
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options # Required for headless
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTestlogin():
  def setup_method(self, method):
    chrome_options = Options()
    chrome_options.add_argument("--headless=new") # Runs without a GUI
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    
    chrome_options.add_argument("--ignore-certificate-errors")
    chrome_options.add_argument("--allow-insecure-localhost")

    self.driver = webdriver.Chrome(options=chrome_options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testlogin(self):
    self.driver.get("http://localhost:5269/") 
    self.driver.set_window_size(1264, 656)
    
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "Input_Email").click()
    self.driver.find_element(By.ID, "Input_Email").send_keys("selenium@etsu.edu")
    self.driver.find_element(By.ID, "Input_Password").send_keys("Selenium1!")
    self.driver.find_element(By.ID, "login-submit").click()
    
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".form-inline > .btn"))
    )