events {}

http {
  client_max_body_size 50M;
  server {
    listen 80;
    server_name etsumarketplace.xyz;

    location / {
      proxy_pass http://etsu-marketplace-app:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 80;
    server_name grafana.etsumarketplace.xyz;

    location / {
      proxy_pass http://grafana-service:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 80;
    server_name prometheus.etsumarketplace.xyz;

    location / {
      proxy_pass http://prometheus-service:9090;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
